Reorder parameters for create snapshot and change defaults
electric-cloud/EF-Utilities pull request #44
Opened 2016-09-26 15:33 UTC by imago-storm

2016-09-27 18:19 UTC, urvashisingh requested changes

2016-09-27 18:19 UTC, urvashisingh commented on src/main/resources/project/parameterForms/CreateSnapshot.xml
> +        <documentation>Name of the project that contains the environment, if different from the application project.</documentation>
Add a default for the Environment project name also per Vinoo's comment:

 <value>$[/myEnvironment/projectName]</value>

2016-09-28 07:51 UTC, imago-storm commented on src/main/resources/project/parameterForms/CreateSnapshot.xml
> +        <documentation>Name of the project that contains the environment, if different from the application project.</documentation>
Done

2016-09-28 07:51 UTC, imago-storm commented on src/main/resources/project/parameterForms/CreateSnapshot.xml
> +        <documentation>Name of the project that contains the environment, if different from the application project.</documentation>
Done

2016-09-28 16:52 UTC, urvashisingh approved these changes

2016-09-28 16:53 UTC, merged